### ISSUE TITLE
Double tap without a TextField

### ISSUE THREAD

**Issue by AlexanderThiele** [Code-Growers/apple_pencil_double_tap#1]
Hi!
Many thanks for this plugin. I have just tested it and realized that it only works for a text field. 

Do you think it is possible that it could also work without a text field?

**Comment by AlexanderThiele** [comment]
Ah, found out it's not working with iOS 17.5 anymore.

There are 2 new methods:
```swift
    @available(iOS 17.5, *)
    public func pencilInteraction(_ interaction: UIPencilInteraction, didReceiveTap tap: UIPencilInteraction.Tap) {
        print(tap);
    }
    
    @available(iOS 17.5, *)
    public func pencilInteraction(_ interaction: UIPencilInteraction, didReceiveSqueeze squeeze: UIPencilInteraction.Squeeze) {
        print(squeeze);
    }
```

**Comment by NomiAdam** [comment]
Hey @AlexanderThiele 👋, I'm sorry to hear that you had issues with this plugin. 

SadlyI haven't been very active in following the iOS updates, it is great that you have been able to solve this issues 🚀. I have seen the changes in your fork, would you mind if I used your changes as an inspiration to update this plugin so other can benefit your hard work? 

Thanks a lot!

**Comment by AlexanderThiele** [comment]
Hi @NomiAdam 
let me create a PR and you can finalize the code and maybe create an update?
